### PR TITLE
synchronized with glfw 3.2.1

### PR DESCRIPTION
**Pull request by joe9**
I could not figure out the Vulkan bindings hence left them commented out.

@cloudhead @schell @bsl @JavierJF : Can you merge this pull request, please?

### CODE REVIEW

**Comment by cloudhead** [comment]
Thanks for looking into this. There are several reasons though why this can't be merged as it is: you've replaced the vendored glfw with a submodule, which is an unrelated change that would need discussion. As far as 3.2.1 support, we cannot advertise it without vulkan support. I'd suggest updating glfw to `3.1.2` like mentioned in the issue, since there are no API changes, GLFW-b would not be behind either.

**Comment by joe9** [comment]
I understand your rationale. The code fits my purpose and I cannot spend any more time on this. I am sure this can help the next person coming along to do the migration.

**Comment by cloudhead** [comment]
Yes, please let us know if you encounter any problems though as it might be useful when we're in the process of upgrading.

**Comment by JavierJF** [comment]
I can't add much more info to what @cloudhead said.  Thanks for contributing, maybe we could use this in the future. And also feel free to join us at the Gitter channe, so maybe we could sync our efforts better. Very soon we will publish a roadmap with all the detailed info to follow the development, for now, I'm closing this.

**Comment by joe9** [comment]
my 2 cents, there are 5'ish vulkan functions with 3 data structures. It is not a big task, imho. I think it might be easier to just decipher them to bindings instead of putting it off.

**Pull request closed without merging**
